#+TITLE: Home
#+AUTHOR: fauzy
#+OPTIONS: toc:nil num:nil

#+begin_src text
    -----BEGIN GEEK CODE BLOCK-----
    Version: 3.1
    GC/CS/E/FA/L/U d(++)?pu s(--): !a C++$>$ UBL++++>$ P+ L+++(++++)$>$ E+++ W++(+++)$>$ !N* !o K--? !w--(---) O? !M V PS PE Y PGP++ !t 5 X R tv b+ DI D+ G e>++ h++ !r? !z?
    ------END GEEK CODE BLOCK------ 
#+end_src



"When we draw a line down the center of a page, we know who we are if we’re on the
right side and who we are if we’re on the left side. But we don’t know who we are when
we don’t put ourselves on either side. Then we just don’t know what to do. We just
don’t know. We have no reference point, no hand to hold. At that point we can either
freak out or settle in. Contentment is a synonym for loneliness, cool loneliness, settling
down with cool loneliness. We give up believing that being able to escape our loneliness
is going to bring any lasting happiness or joy or sense of well-being or courage or
strength. Usually we have to give up this belief about a billion times, again and again
making friends with our jumpiness and dread, doing the same old thing a billion times
with awareness. Then without our even noticing, something begins to shift. We can just
be lonely with no alternatives, content to be right here with the mood and texture of
what’s happening."


** Recent Post

#+BEGIN_EXPORT html
<div id="recent-posts"></div>
#+END_EXPORT


#+begin_export html
<div class="last-con"><p class="label">Last Updated: <i class="label-date"><2026-08-22 Sat></i></p></div>
#+end_export
